TARGET = $(shell basename $(shell pwd))

SRCS := $(shell ls *.cpp)

CFLAGS += -Wall -Werror -std=c++11 -g -fdiagnostics-color=auto

LDFLAGS ?=

LOCAL_LDFLAGS =

export CFLAGS
export LDFLAGS

include ../Makefile
